name: Test Packages
# This workflow tests the latest (third-party hosted) available builds

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  schedule:
    - cron:  '0 23 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash


jobs:
  test-wheel:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test packages') || github.event_name == 'schedule' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package:
          - engine
          - utils
          - control/multi_object_search
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Wheel
      run: |
        export DISABLE_BCOLZ_AVX2=true
        sudo apt -y install python3.8-venv libfreetype6-dev git build-essential cmake python3-dev wget libopenblas-dev libsndfile1 libboost-dev python3-dev
        python3 -m venv venv
        source venv/bin/activate
        wget https://raw.githubusercontent.com/opendr-eu/opendr/master/dependencies/pip_requirements.txt
        cat pip_requirements.txt | xargs -n 1 -L 1 pip install
        pip install opendr-toolkit
        python -m unittest discover -s tests/sources/tools/${{ matrix.package }}
  test-docker:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test packages') || github.event_name == 'schedule' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package:
          - engine
          - utils
          - control/multi_object_search
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Docker
      run: |
        docker run --name toolkit -i opendr/opendr-toolkit:cpu_v1.1.1 bash
        docker start toolkit
        docker exec -i toolkit bash -c "source bin/activate.sh && source tests/sources/tools/control/mobile_manipulation/run_ros.sh && python -m unittest discover -s tests/sources/tools/${{ matrix.package }}"
